<?php

return array
(
    '^(logout)$' => 'user/logout',
    '^(login)$' => 'user/signIn',
    '^(registration)$' => 'user/signUp',
    'main/page/([0-9]+)' => 'main/index',
    '^(main)$' => 'main/index',
    '^(profile/edit)$' => 'profile/edit',
    'profile/([a-zA-Zа-яА-ЯёЁр-цР-Ц0-9_.-]+)' => 'profile/view/$1',
    'validation' => 'validation/index',
    '^(event/add)$' => 'event/add',
    '^(sendRequest)$' => 'request/sendRequest',
    'event/current/page/([0-9]+)' => 'event/current',
    '^(event/current)$' => 'event/current',
    'event/archive/page/([0-9]+)' => 'event/archive',
    '^(event/archive)$' => 'event/archive',
    'event/([0-9]+)/request' => 'request/view/$1',
    '^(account/security)$' => 'accountSecurity/view',
    '^(save/email)$' => 'user/saveEmail',
    '^(passwordRecovery)$' => 'accountSecurity/passwordRecovery',
    '^(userApiDelete)$' => 'admin\BaseEntity/DeleteRecordFromTheTable',
    '^(allDataApiRequest)$' => 'admin\BaseEntity/getDataTable',
    '^(EventCreateApi)$' => 'admin\EventEntity/createEvent',
    '^(eventAuthorIdentification)$' => 'admin\RequestEntity/identifyTheEventAuthor',
    '^(RequestCreateApi)$' => 'admin\RequestEntity/createRequest',
    '^(UserCreateApi)$' => 'admin\UserEntity/createUser',
    '^(userChangeRole)$' => 'admin\UserEntity/changeUserRole',
    '^(EventGetDataById)$' => 'admin\EventEntity/getEventDataById',
    '^(userApiCheckAdminRights)$' => 'admin\BaseEntity/checkAdminStatus'
    //'Profile/([a-z,0-9]+)/comments' =>  ,
    //'Profile/([a-z,0-9]+)/comments/add' =>  ,
    //'Profile/([a-z,0-9]+)/comments/([0-9]+)/edit' =>  ,
    //'event/add' => ,
    //'event/([0-9]+)' =>   ,
    //'event/([0-9]+)/edit' =>   ,
    //'event/([0-9]+)/request' =>   ,
    //'event/current' =>   ,
    //'event/archive' =>   ,

);
